name: rentamate_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  avatar_glow: 2.0.1
  cupertino_icons: ^1.0.2
  faker: 2.0.0
  flutter:
    sdk: flutter
  get: 4.3.8
  get_storage: 2.0.3
  google_fonts: ^3.0.1
  introduction_screen: 2.1.0
  lottie: 1.2.1
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
    - assets/logo/
    - assets/img/
    - assets/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  uses-material-design: true
